[mainConfig]
appName = "GopherAI"
host = "0.0.0.0"
port = 9090

[emailConfig]
authcode = "mhyifjsrkkmkcede"
email = "nishuixunzhou@qq.com"

[redisConfig]
host = "127.0.0.1"
port = 6379
password = ""
db = 0

[mysqlConfig]
host = "127.0.0.1"
port = 3306
user = "root"
password = "123456"
databaseName = "AgentGo"
charset =  "utf8mb4"

[jwtConfig]
 expire_duration= 8760
 issuer= "huanheart"
 subject= "GopherAI"
 key= "GopherAI-v1"

[adminConfig]
username = "admin"
password = "admin"
email = "admin@gopherai.local"

 [rabbitmqConfig]
  host= "127.0.0.1"
  port= 5672
  username= "root"
  password= "123456"
  vhost= "/"

[qwenConfig]
apiKey = "sk-2cd35d5c33e3415ba9f23ce67795364c"
baseURL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
modelName = "qwen-plus"

[deepseekConfig]
apiKey = "sk-d126528801794cc5b47d96e83a80c2be"
baseURL = "https://api.deepseek.com"
modelName = "deepseek-chat"
